services:
  environment_event_subscriber:
    class: Drupal\environment\EventSubscriber\EnvironmentSubscriber
    tags:
      - {name: event_subscriber}

    environment.environment_service:
      class: Drupal\environment\EnvironmentService